---
title: "Proceso Electoral 2021"
css: custom.css
---

## Proceso Electoral 2021:

```{r}
library(tidyverse)
library(readxl)
library(reactable)
options(scipen=999)
options(digits=2)
```

```{r}
dipfed2021 <- read_excel("C:/Users/Eduardo/Documents/PC/SECCION1/DOCS/Tesis/FEDERAL/diputaciones 2021.xlsx")
dipfed2021
```

```{r}
dipfed2021 <- dipfed2021%>%
select(-ID_DISTRITO_FEDERAL, -CABECERA_DISTRITAL_FEDERAL, -NUM_VOTOS_CAN_NREG, -SECCIONES, -CASILLAS, -TRIBUNAL, -JUICIO, -OBSERVACIONES, -RUTA_ACTA)

reactable(dipfed2021)
```

### Manipulación de Datos:

```{r}
dipfed2021 <- dipfed2021%>%
gather(key=Partido, value=Votos, PAN:CAND_IND3)

reactable(dipfed2021)
```

### Agrupaciones:

```{r}
dipfed2021_1 <- dipfed2021%>%
  group_by(ID_ESTADO, NOMBRE_ESTADO, Partido)%>%
  reframe(Votos = sum(Votos),
         LISTA_NOMINAL = sum(LISTA_NOMINAL),
         TOTAL_VOTOS = sum(TOTAL_VOTOS),
         NUM_VOTOS_NULOS = sum(NUM_VOTOS_NULOS))%>%
  arrange((ID_ESTADO))

reactable(dipfed2021_1) 
```

```{r}
dipfed2021_1 <- dipfed2021_1[!is.na(dipfed2021_1$Votos),]
```

```{r}
reactable(dipfed2021_1)
```

### Agrupaciones:

```{r}
suma_F2021 <- dipfed2021_1%>%
            group_by(ID_ESTADO, NOMBRE_ESTADO)%>%
            reframe(Votos1 = sum(Votos))

reactable(suma_F2021)
```

### Uniones:

```{r}
dipfed2021_1_f <- dipfed2021_1 %>%
    left_join(suma_F2021, by = c("ID_ESTADO", "NOMBRE_ESTADO"))

reactable(dipfed2021_1_f)
```

```{r}
dipfed2021_1_f <- dipfed2021_1_f%>%
    mutate(Proporcion= (Votos/Votos1)*(100))

dipfed2021_1_f
```

```{r}
dipfed2021_1_f <- dipfed2021_1_f%>%
mutate(Partido = ifelse(Partido == "FXM", "Otro", Partido))%>%
mutate(Partido = ifelse(Partido == "PES", "Otro", Partido))%>%
mutate(Partido = ifelse(Partido == "RSP", "Otro", Partido))
```

```{r}
reactable(dipfed2021_1_f)
```

### Agrupaciones:

```{r}
dipfed2021_2_f  <- dipfed2021_1_f%>%
group_by(Partido)%>%
reframe(sum(Votos),
          sum(Proporcion/32))

dipfed2021_2_f
```

```{r}
dipfed2021_2_f <- dipfed2021_2_f%>%
rename(Votos = `sum(Votos)`, 
      Proporcion = `sum(Proporcion/32)`)
dipfed2021_2_f
```

```{r}
integrantes2021 <- read_excel ("C:/Users/Eduardo/Documents/PC/SECCION1/DOCS/Tesis/Integrantes/diputados_federales.xlsx")
reactable(integrantes2021)
```

```{r}
integrantes2021 <- integrantes2021%>%
filter(Año == 2021)

reactable(integrantes2021)
```

```{r}
table(integrantes2021$Partido)
table(dipfed2021_2_f$Partido)
```

```{r}
integrantes2021 <- integrantes2021%>%
mutate(Partido = ifelse(Partido == "SP", "Otro", Partido))

reactable(integrantes2021)
```

### Uniones:

```{r}
dipfed2021_1_f1 <- dipfed2021_2_f%>%
inner_join(integrantes2021, by= "Partido") 

reactable(dipfed2021_1_f1)
```

### Presentación de Tibble:

```{r}
dipfed2021_1_f1 <- dipfed2021_1_f1%>%
gather(key = Sexo, value = Curules, Hombres:Mujeres)

reactable(dipfed2021_1_f1)
```
